CREATE TABLE IF NOT EXISTS classification (cId INTEGER PRIMARY KEY, classification TEXT, description TEXT);
INSERT INTO classification(classification, description) VALUES('Ma', 'Marilyn');
INSERT INTO classification(classification, description) VALUES('Hu', 'Hump');
INSERT INTO classification(classification, description) VALUES('Sim', 'Simm');
INSERT INTO classification(classification, description) VALUES('5', 'Dodd');
INSERT INTO classification(classification, description) VALUES('M', 'Munro');
INSERT INTO classification(classification, description) VALUES('MT', 'Munro Top');
INSERT INTO classification(classification, description) VALUES('F', 'Furth');
INSERT INTO classification(classification, description) VALUES('C', 'Corbett');
INSERT INTO classification(classification, description) VALUES('G', 'Graham');
INSERT INTO classification(classification, description) VALUES('D', 'Donald');
INSERT INTO classification(classification, description) VALUES('DT', 'Donald Top');
INSERT INTO classification(classification, description) VALUES('Hew', 'Hewitt');
INSERT INTO classification(classification, description) VALUES('N', 'Nuttall');
INSERT INTO classification(classification, description) VALUES('Dew', 'Dewey');
INSERT INTO classification(classification, description) VALUES('DDew', 'Donald Dewey');
INSERT INTO classification(classification, description) VALUES('HF', 'Highland Five');
INSERT INTO classification(classification, description) VALUES('4', '400-499m Tump');
INSERT INTO classification(classification, description) VALUES('3', '300-399m Tump (GB)');
INSERT INTO classification(classification, description) VALUES('2', '200-299m Tump (GB)');
INSERT INTO classification(classification, description) VALUES('1', '100-199m Tump (GB)');
INSERT INTO classification(classification, description) VALUES('0', '0-99m Tump (GB)');
INSERT INTO classification(classification, description) VALUES('W', 'Wainwright');
INSERT INTO classification(classification, description) VALUES('WO', 'Wainwright Outlying Fell');
INSERT INTO classification(classification, description) VALUES('B', 'Birkett');
INSERT INTO classification(classification, description) VALUES('Sy', 'Synge');
INSERT INTO classification(classification, description) VALUES('Fel', 'Fellranger');
INSERT INTO classification(classification, description) VALUES('CoH', 'County Top – Historic (pre-1974)');
INSERT INTO classification(classification, description) VALUES('CoA', 'County Top – Administrative (1974 to mid-1990s)');
INSERT INTO classification(classification, description) VALUES('CoU', 'County Top – Current County or Unitary Authority');
INSERT INTO classification(classification, description) VALUES('CoL', 'County Top – Current London Borough');
INSERT INTO classification(classification, description) VALUES('SIB', 'Significant Island of Britain');
INSERT INTO classification(classification, description) VALUES('Dil', 'Dillon');
INSERT INTO classification(classification, description) VALUES('A', 'Arderin');
INSERT INTO classification(classification, description) VALUES('VL', 'Vandeleur-Lynam');
INSERT INTO classification(classification, description) VALUES('MDew', 'Myrddyn Dewey');
INSERT INTO classification(classification, description) VALUES('O', 'Other list');
INSERT INTO classification(classification, description) VALUES('Un', 'unclassified');